http:
    host: localhost
    port: 8080
database:
    host: localhost
    name: tskrx
    password: 123
    port: 5432
    user: ess
production: false
jwt:
    access_key: secretKeyForJWT
    refresh_key: AnotherSecretKey