http:
    host: localhost
    port: 8080
database:
    host: localhost
    name: tskrx
    password: 123
    port: 5432
    user: ess
redis:
    host:   localhost
    port:   6379
    password:   ""
    db: 0             #default
    poolsize:   10
    dialtimeout:    5 #sec
    readtimeout:    3 #sec
    writetimeout:   3 #sec
    idletimeout:    5 #min
jwt:
    access_key: secretKeyForJWT
    refresh_key: AnotherSecretKey
